// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhsxpxrchqthevkobtfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoc3hweHJjaHF0aGV2a29idGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjExMTQsImV4cCI6MjA1NTkzNzExNH0.D2hWNypwwy9sW-jtOpZX00RhSbMRxT0IWitP1lY7XnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);